=== katieisnell/stendhal/data/conf/actions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/actions" elementFormDefault="qualified"
	xmlns:Q3="stendhal">
	
	<element name="actions" type="Q3:Actions" />
	
	<complexType name="Actions" >
		<sequence>
			<element name="action" type="Q3:Action" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<complexType name="Action">
		<sequence>
			<element name="implementation" type="Q3:Implementation" />
			<element name="type" type="Q3:Type" />
			<element name="number_of_parameters" type="Q3:NumberOfParameters" />
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	
	<complexType name="Implementation">
    		<attribute name="class-name" type="string" />
    </complexType>
    
    <complexType name="Type">
    		<attribute name="value" type="string" />
    </complexType>
    
    <complexType name="NumberOfParameters">
	    	<sequence>
	    		<element name="minimum" type="Q3:parameter_type" />
	    		<element name="maximum" type="Q3:parameter_type" />
	    	</sequence>
    </complexType>
    
    <complexType name="parameter_type">
    		<attribute name="value" type="string" />
    </complexType>
    
	
</schema>

=== katieisnell/stendhal/data/conf/actions/remove_buddy.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../actions.xsd ">
	<action name="remove">
		<implementation class-name="games.stendhal.client.DefaultAction"/>
        <type value="remove"/>
		<param key="target" index="0" />
		<number_of_parameters>
			<minimum value="1" />
			<maximum value="1" />
		</number_of_parameters>
	</action>
</actions>

=== katieisnell/stendhal/data/conf/actions/admin_actions.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../actions.xsd ">
	
	<action name="adminnote">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="adminnote"/>
		<param key="target" index="0" />
		<remainder key="note" canBeEmpty="false"/>
		<number_of_parameters>
			<minimum value="1" />
			<maximum value="1" />
		</number_of_parameters>
	</action>
	
	<action name="inspect">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="inspect"/>
		<param key="target" index="0" />
		<number_of_parameters>
			<minimum value="1" />
			<maximum value="1" />
		</number_of_parameters>
	</action>
	
	<action name="invisible">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="invisible"/>
		<number_of_parameters>
			<minimum value="0" />
			<maximum value="0" />
		</number_of_parameters>
	</action>
	
	<action name="tellall">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="tellall"/>
		<remainder key="text" canBeEmpty="false"/>
		<number_of_parameters>
			<minimum value="0" />
			<maximum value="0" />
		</number_of_parameters>
	</action>
	
</actions>

=== katieisnell/stendhal/data/conf/actions/auto_walk.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../actions.xsd ">
	<action name="walk">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="walk"/>
		<remainder key="target" canBeEmpty="true" />
		<number_of_parameters>
			<minimum value="0" />
			<maximum value="0" />
		</number_of_parameters>
	</action>
</actions>

=== katieisnell/stendhal/data/conf/actions/information.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../actions.xsd ">
	
	<action name="listproducers">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="listproducers"/>
		<number_of_parameters>
			<minimum value="0" />
			<maximum value="0" />
		</number_of_parameters>
	</action>
	
	<action name="progressstatus">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="progressstatus"/>
		<number_of_parameters>
			<minimum value="0" />
			<maximum value="0" />
		</number_of_parameters>
	</action>
	
	<action name="where">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="where"/>
		<remainder key="target" canBeEmpty="false"/>
		<number_of_parameters>
			<minimum value="0" />
			<maximum value="0" />
		</number_of_parameters>
	</action>
	
	<action name="who">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="who"/>
		<number_of_parameters>
			<minimum value="0" />
			<maximum value="0" />
		</number_of_parameters>
	</action>
	
</actions>

=== katieisnell/stendhal/data/conf/actions/social.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../actions.xsd ">
	
	<action name="emote">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="emote"/>
		<remainder key="text" canBeEmpty="false" />			
		<number_of_parameters>
			<minimum value="0" />
			<maximum value="0" />
		</number_of_parameters>
	</action>
	
	<action name="tell">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="tell"/>
        <param key="target" index="0" />
		<remainder key="text" canBeEmpty="false"/>
		<number_of_parameters>
			<minimum value="1" />
			<maximum value="1" />
		</number_of_parameters>
	</action>
	
	<action name="remove">
		<implementation class-name="games.stendhal.client.DefaultAction"/>
        <type value="remove"/>
		<param key="target" index="0" />
		<number_of_parameters>
			<minimum value="1" />
			<maximum value="1" />
		</number_of_parameters>
	</action>
	
	<action name="sentence">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="sentence"/>
		<remainder key="value" canBeEmpty="true" />
		<number_of_parameters>
			<minimum value="0" />
			<maximum value="0" />
		</number_of_parameters>
	</action>
	
	<action name="storemessage">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="storemessage"/>
		<param key="target" index="0" />
		<remainder key="text" canBeEmpty="false" />
		<number_of_parameters>
			<minimum value="1" />
			<maximum value="1" />
		</number_of_parameters>
	</action>
	
</actions>

=== katieisnell/stendhal/data/conf/actions/group_management.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../actions.xsd ">
	
	<action name="groupmanagement">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="groupmanagement"/>
        <param key="action" index="0" />
		<remainder key="params" canBeEmpty="false" />
		<number_of_parameters>
			<minimum value="1" />
			<maximum value="1" />
		</number_of_parameters>
	</action>
	
	<action name="group_message">
		<implementation class-name="games.stendhal.client.actions.DefaultAction"/>
		<type value="group_message"/>
		<remainder key="text" canBeEmpty="false" />
		<number_of_parameters>
			<minimum value="0" />
			<maximum value="0" />
		</number_of_parameters>
	</action>
	
</actions>
